from setuptools import setup, find_packages
with open("README.md", "r", encoding="utf-8") as f:
    long_description = f.read()
setup(
    name="omnirag",
    version="2.0.2",
    author="Girinath V",
    author_email="girinathv48@gmail.com",
    description="Multi-Language Voice RAG Framework",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/Giri530/omnirag",
    project_urls={
        "Bug Tracker": "https://github.com/Giri530/omnirag/issues",
        "Documentation": "https://github.com/Giri530/omnirag#readme",
        "Source Code": "https://github.com/Giri530/omnirag",
    },
    packages=["omnirag"],
    package_data={
        "omnirag": ["*.py"],
    },
    include_package_data=True,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
    install_requires=[
        "transformers>=4.30.0",
        "torch>=2.0.0",
        "sentence-transformers>=2.2.0",
        "faiss-cpu>=1.7.4",
        "numpy>=1.24.0",
        "accelerate>=0.20.0",
        "PyPDF2>=3.0.0",
        "ddgs>=0.3.0",
        "requests>=2.31.0",
        "deep-translator>=1.11.4",
        "langdetect>=1.0.9",
        "pyttsx3>=2.90",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "black>=22.0.0",
            "flake8>=4.0.0",
            "twine>=4.0.0",
            "build>=0.10.0",
        ],
        "voice-input": [
            "SpeechRecognition>=3.10.0",
            "pyaudio>=0.2.13",
        ],
    },
    keywords=[
        "rag",
        "retrieval-augmented-generation",
        "llm",
        "ai",
        "machine-learning",
        "nlp",
        "multi-language",
        "voice",
        "tamil",
        "hindi",
        "translation",
        "faiss",
        "vector-database",
        "qwen",
        "huggingface",
    ],
)
